services:
  - type: web
    name: auth-service
    env: node
    plan: free
    rootDir: services/auth-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: dashboard-service
    env: node
    plan: free
    rootDir: services/dashboard-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5002
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: project-service
    env: node
    plan: free
    rootDir: services/project-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5003
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false