import pool from '../../db.js';

const BREVO_API_URL = 'https://api.brevo.com/v3/smtp/email';
const NOTIFICATION_LIMIT = 30;

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDueAt(dueAt) {
  if (!dueAt) return '';
  const d = new Date(dueAt);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleString(undefined, {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * In-app notifications feed + due-date email sender.
 *
 * Rows are generated by the `generate_due_notifications()` RPC (pg_cron,
 * migration 011). This module only reads/updates rows and sends the emails
 * for rows that have emailed = false.
 */
export class Notifications {
  /**
   * Recent notifications for a user, unread first, plus the unread count
   * for the bell badge. Also flushes pending emails opportunistically —
   * the service is guaranteed awake while handling this request, so any
   * unsent emails go out instead of waiting for the hourly pg_net poke.
   *
   * @param {string} email  Owner email
   * @returns {{success: boolean, data?: {notifications: Array, unreadCount: number}, message?: string}}
   */
  async getNotifications(email) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email) return { success: false, message: 'email is required' };

      const { rows } = await pool.query(
        `SELECT id, entry_id, project_name, entry_title, type, due_at, read, created_at
           FROM public.notifications
          WHERE user_email = $1
          ORDER BY read ASC, created_at DESC
          LIMIT $2`,
        [email, NOTIFICATION_LIMIT]
      );

      const { rows: countRows } = await pool.query(
        `SELECT COUNT(*)::int AS count
           FROM public.notifications
          WHERE user_email = $1 AND read = false`,
        [email]
      );

      // Opportunistic email flush (not awaited): the service is awake right
      // now, so pending emails go out within a poll interval of any active
      // session instead of waiting for the hourly pg_net poke.
      this.sendPendingEmails().catch((err) =>
        console.error('[getNotifications] pending-email flush failed:', err.message)
      );

      return {
        success: true,
        data: { notifications: rows, unreadCount: countRows[0]?.count ?? 0 },
      };
    } catch (err) {
      console.error('[getNotifications] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Mark a single notification as read. Scoped to the owner so one user
   * cannot clear another user's feed.
   */
  async markRead(email, notificationId) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email || !notificationId) {
        return { success: false, message: 'email and notificationId are required' };
      }

      const { rowCount } = await pool.query(
        `UPDATE public.notifications
            SET read = true
          WHERE id = $1 AND user_email = $2`,
        [notificationId, email]
      );

      if (rowCount === 0) {
        return { success: false, message: 'Notification not found' };
      }
      return { success: true, message: 'Notification marked as read' };
    } catch (err) {
      console.error('[markRead] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Mark every notification in the user's feed as read.
   */
  async markAllRead(email) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email) return { success: false, message: 'email is required' };

      await pool.query(
        `UPDATE public.notifications
            SET read = true
          WHERE user_email = $1 AND read = false`,
        [email]
      );
      return { success: true, message: 'All notifications marked as read' };
    } catch (err) {
      console.error('[markAllRead] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Send an email for every pending notification whose owner has email
   * notifications enabled, then mark the row emailed = true (or, for
   * opted-out owners, mark it emailed without sending so a later
   * re-enable never back-fills a backlog).
   *
   * Called without a user JWT — the trigger is the hourly pg_cron/pg_net
   * poke (migration 011) or an opportunistic flush during getNotifications.
   * It is idempotent: already-emailed rows are never re-sent, and users who
   * opt out never receive anything, so unauthenticated triggering cannot
   * make the service send mail it would not otherwise send.
   *
   * @returns {{success: boolean, sent?: number, skipped?: number, message?: string}}
   */
  async sendPendingEmails() {
    try {
      if (!pool) throw new Error('Database pool not initialized');

      const apiKey = process.env.BREVO_API_KEY;
      const senderEmail = process.env.BREVO_SENDER_EMAIL;
      if (!apiKey || !senderEmail) {
        return {
          success: false,
          message: 'BREVO_API_KEY / BREVO_SENDER_EMAIL not configured',
        };
      }

      // FOR UPDATE SKIP LOCKED: the cron poke and app-traffic flush can run
      // concurrently — lock claimed rows so two senders never mail the same
      // notification.
      const { rows: pending } = await pool.query(
        `SELECT n.id, n.user_email, n.project_name, n.entry_title, n.type, n.due_at,
                COALESCE(u.email_notifications, true) AS email_enabled
           FROM public.notifications n
           LEFT JOIN public.users u ON u.email = n.user_email
          WHERE n.emailed = false
          ORDER BY n.created_at ASC
          LIMIT 200
          FOR UPDATE OF n SKIP LOCKED`
      );

      let sent = 0;
      let skipped = 0;

      for (const row of pending) {
        // email_enabled is COALESCE'd to true in SQL; only an explicit
        // false (user opted out) skips sending.
        if (row.email_enabled === false) {
          await pool.query(`UPDATE public.notifications SET emailed = true WHERE id = $1`, [
            row.id,
          ]);
          skipped += 1;
          continue;
        }

        const delivered = await this._sendBrevoEmail(apiKey, senderEmail, row);
        if (delivered) {
          await pool.query(`UPDATE public.notifications SET emailed = true WHERE id = $1`, [
            row.id,
          ]);
          sent += 1;
        }
      }

      console.log(`[sendPendingEmails] sent=${sent} skipped=${skipped}`);
      return { success: true, sent, skipped };
    } catch (err) {
      console.error('[sendPendingEmails] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Single transactional email via the Brevo HTTP API (no SMTP needed).
   * Returns true only when Brevo accepted the message.
   */
  async _sendBrevoEmail(apiKey, senderEmail, row) {
    const isOverdue = row.type === 'overdue';
    const title = row.entry_title || `${row.project_name || 'An'} entry`;
    const dueLabel = formatDueAt(row.due_at);
    const subject = isOverdue ? `Overdue: ${title}` : `Due soon: ${title}`;
    const heading = isOverdue ? 'You missed a deadline' : 'A deadline is approaching';
    const bodyText = isOverdue
      ? `"${title}" was due ${dueLabel || 'recently'} and is still open.`
      : `"${title}" is due ${dueLabel || 'within the next 24 hours'}.`;

    const html = `
      <div style="font-family: Arial, Helvetica, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
        <h2 style="color: #1f2933; margin: 0 0 12px;">Digital Logbook</h2>
        <p style="color: #1f2933; font-size: 16px; margin: 0 0 8px;">${heading}</p>
        <p style="color: #4b5563; font-size: 14px; line-height: 1.5; margin: 0 0 16px;">
          ${escapeHtml(bodyText)}
          ${row.project_name ? `<br/>Project: <strong>${escapeHtml(row.project_name)}</strong>` : ''}
        </p>
        <p style="color: #6b7280; font-size: 12px; margin: 0;">
          You're receiving this because email notifications are enabled in your
          Digital Logbook settings. Open the app to view or manage this entry.
        </p>
      </div>`;

    try {
      const response = await fetch(BREVO_API_URL, {
        method: 'POST',
        headers: {
          'api-key': apiKey,
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify({
          sender: { email: senderEmail, name: 'Digital Logbook' },
          to: [{ email: row.user_email }],
          subject,
          htmlContent: html,
        }),
      });

      if (!response.ok) {
        const body = await response.text();
        console.error(`[sendPendingEmails] Brevo rejected ${row.id}: ${response.status} ${body}`);
        return false;
      }
      return true;
    } catch (err) {
      console.error(`[sendPendingEmails] Brevo call failed for ${row.id}:`, err.message);
      return false;
    }
  }
}

export default Notifications;
