import pool from '../../db.js';

const BREVO_API_URL = 'https://api.brevo.com/v3/smtp/email';
const APP_URL = 'https://digital-logbook-bxgv.onrender.com';
const NOTIFICATION_LIMIT = 30;
const HISTORY_PAGE_SIZE = 50;
const HISTORY_MAX_LIMIT = 200;

/** Valid snooze durations — mapped to SQL interval expressions. */
const SNOOZE_INTERVALS = {
  '1h': '1 hour',
  '4h': '4 hours',
  tomorrow: "date_trunc('day', now() + interval '1 day') + interval '8 hours'",
};

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDueAt(dueAt) {
  if (!dueAt) return '';
  const d = new Date(dueAt);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleString(undefined, {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * In-app notifications feed + due-date email sender.
 *
 * Rows are generated by the `generate_due_notifications()` RPC (pg_cron,
 * migration 011). This module only reads/updates rows and sends the emails
 * for rows that have emailed = false.
 */
export class Notifications {
  /**
   * Recent notifications for a user, unread first, plus the unread count
   * for the bell badge. Also flushes pending emails opportunistically —
   * the service is guaranteed awake while handling this request, so any
   * unsent emails go out instead of waiting for the hourly pg_net poke.
   *
   * @param {string} email  Owner email
   * @returns {{success: boolean, data?: {notifications: Array, unreadCount: number}, message?: string}}
   */
  async getNotifications(email) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email) return { success: false, message: 'email is required' };

      const { rows } = await pool.query(
        `SELECT id, entry_id, project_name, entry_title, type, due_at, read, created_at, snoozed_until
           FROM public.notifications
          WHERE user_email = $1
            AND dismissed = false
            AND (snoozed_until IS NULL OR snoozed_until > now())
          ORDER BY read ASC, created_at DESC
          LIMIT $2`,
        [email, NOTIFICATION_LIMIT]
      );

      const { rows: countRows } = await pool.query(
        `SELECT COUNT(*)::int AS count
           FROM public.notifications
          WHERE user_email = $1
            AND read = false
            AND dismissed = false
            AND (snoozed_until IS NULL OR snoozed_until > now())`,
        [email]
      );

      // Opportunistic email flush (not awaited): the service is awake right
      // now, so pending emails go out within a poll interval of any active
      // session instead of waiting for the hourly pg_net poke.
      this.sendPendingEmails().catch((err) =>
        console.error('[getNotifications] pending-email flush failed:', err.message)
      );

      return {
        success: true,
        data: { notifications: rows, unreadCount: countRows[0]?.count ?? 0 },
      };
    } catch (err) {
      console.error('[getNotifications] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Full notification history for the dedicated /notifications page —
   * every row still stored for the user (read and unread), newest first,
   * paginated. Read rows are pruned after 30 days by the cron job in
   * migration 011, so "entire history" means everything the table holds.
   *
   * @param {string} email  Owner email
   * @param {number} limit  Page size (clamped 1..200, default 50)
   * @param {number} offset Rows to skip (default 0)
   * @returns {{success: boolean, data?: {notifications: Array, total: number, limit: number, offset: number}, message?: string}}
   */
  /**
   * Full notification history with optional server-side filters.
   *
   * @param {string} email       Owner email
   * @param {number} limit       Page size (clamped 1..200, default 50)
   * @param {number} offset      Rows to skip (default 0)
   * @param {object} [filters]   Optional: { unreadOnly: boolean, type: 'due_soon'|'overdue' }
   */
  async getHistory(email, limit = HISTORY_PAGE_SIZE, offset = 0, filters = {}) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email) return { success: false, message: 'email is required' };

      const parsedLimit = Number.parseInt(limit, 10);
      const parsedOffset = Number.parseInt(offset, 10);
      const safeLimit = Math.min(
        Math.max(Number.isNaN(parsedLimit) ? HISTORY_PAGE_SIZE : parsedLimit, 1),
        HISTORY_MAX_LIMIT
      );
      const safeOffset = Math.max(Number.isNaN(parsedOffset) ? 0 : parsedOffset, 0);

      // Build dynamic WHERE clauses for optional filters
      const conditions = ['user_email = $1', 'dismissed = false'];
      const params = [email];
      if (filters.unreadOnly) {
        conditions.push('read = false');
      }
      if (filters.type === 'due_soon' || filters.type === 'overdue') {
        params.push(filters.type);
        conditions.push(`type = $${params.length}`);
      }
      const whereClause = conditions.join(' AND ');

      const { rows } = await pool.query(
        `SELECT id, entry_id, project_name, entry_title, type, due_at, read, created_at, snoozed_until
           FROM public.notifications
          WHERE ${whereClause}
          ORDER BY created_at DESC
          LIMIT $${params.length + 1} OFFSET $${params.length + 2}`,
        [...params, safeLimit, safeOffset]
      );

      const { rows: totalRows } = await pool.query(
        `SELECT COUNT(*)::int AS count FROM public.notifications WHERE ${whereClause}`,
        params
      );

      return {
        success: true,
        data: {
          notifications: rows,
          total: totalRows[0]?.count ?? 0,
          limit: safeLimit,
          offset: safeOffset,
        },
      };
    } catch (err) {
      console.error('[getHistory] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Mark a single notification as read. Scoped to the owner so one user
   * cannot clear another user's feed.
   */
  async markRead(email, notificationId) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email || !notificationId) {
        return { success: false, message: 'email and notificationId are required' };
      }

      const { rowCount } = await pool.query(
        `UPDATE public.notifications
            SET read = true
          WHERE id = $1 AND user_email = $2`,
        [notificationId, email]
      );

      if (rowCount === 0) {
        return { success: false, message: 'Notification not found' };
      }
      return { success: true, message: 'Notification marked as read' };
    } catch (err) {
      console.error('[markRead] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Mark every notification in the user's feed as read.
   */
  async markAllRead(email) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email) return { success: false, message: 'email is required' };

      await pool.query(
        `UPDATE public.notifications
            SET read = true
          WHERE user_email = $1 AND read = false`,
        [email]
      );
      return { success: true, message: 'All notifications marked as read' };
    } catch (err) {
      console.error('[markAllRead] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Send an email for every pending notification whose owner has email
   * notifications enabled, then mark the row emailed = true (or, for
   * opted-out owners, mark it emailed without sending so a later
   * re-enable never back-fills a backlog).
   *
   * Called without a user JWT — the trigger is the hourly pg_cron/pg_net
   * poke (migration 011) or an opportunistic flush during getNotifications.
   * It is idempotent: already-emailed rows are never re-sent, and users who
   * opt out never receive anything, so unauthenticated triggering cannot
   * make the service send mail it would not otherwise send.
   *
   * @returns {{success: boolean, sent?: number, skipped?: number, message?: string}}
   */
  async sendPendingEmails() {
    try {
      if (!pool) throw new Error('Database pool not initialized');

      const apiKey = process.env.BREVO_API_KEY;
      const senderEmail = process.env.BREVO_SENDER_EMAIL;
      if (!apiKey || !senderEmail) {
        return {
          success: false,
          message: 'BREVO_API_KEY / BREVO_SENDER_EMAIL not configured',
        };
      }

      // FOR UPDATE SKIP LOCKED: the cron poke and app-traffic flush can run
      // concurrently — lock claimed rows so two senders never mail the same
      // notification.
      const { rows: pending } = await pool.query(
        `SELECT n.id, n.user_email, n.project_name, n.entry_title, n.type, n.due_at,
                COALESCE(u.email_notifications, true) AS email_enabled
           FROM public.notifications n
           LEFT JOIN public.users u ON u.email = n.user_email
          WHERE n.emailed = false
          ORDER BY n.created_at ASC
          LIMIT 200
          FOR UPDATE OF n SKIP LOCKED`
      );

      let sent = 0;
      let skipped = 0;

      for (const row of pending) {
        // email_enabled is COALESCE'd to true in SQL; only an explicit
        // false (user opted out) skips sending.
        if (row.email_enabled === false) {
          await pool.query(`UPDATE public.notifications SET emailed = true WHERE id = $1`, [
            row.id,
          ]);
          skipped += 1;
          continue;
        }

        const delivered = await this._sendBrevoEmail(apiKey, senderEmail, row);
        if (delivered) {
          await pool.query(`UPDATE public.notifications SET emailed = true WHERE id = $1`, [
            row.id,
          ]);
          sent += 1;
        }
      }

      console.log(`[sendPendingEmails] sent=${sent} skipped=${skipped}`);
      return { success: true, sent, skipped };
    } catch (err) {
      console.error('[sendPendingEmails] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Snooze a notification — hides it from the bell feed until the snooze
   * expires, then the cron generator re-surfaces it as unread.
   *
   * @param {string} email           Owner email
   * @param {string} notificationId  Notification UUID
   * @param {string} duration        '1h' | '4h' | 'tomorrow'
   */
  async snooze(email, notificationId, duration) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email || !notificationId || !duration) {
        return { success: false, message: 'email, notificationId and duration are required' };
      }

      const intervalExpr = SNOOZE_INTERVALS[duration];
      if (!intervalExpr) {
        return {
          success: false,
          message: `Invalid duration: ${duration}. Use 1h, 4h, or tomorrow.`,
        };
      }

      // For simple intervals, use now() + interval; for 'tomorrow', use the
      // date_trunc expression from SNOOZE_INTERVALS.
      const snoozeExpr =
        duration === 'tomorrow' ? intervalExpr : `now() + interval '${intervalExpr}'`;

      const { rowCount } = await pool.query(
        `UPDATE public.notifications
            SET snoozed_until = ${snoozeExpr}, read = true
          WHERE id = $1 AND user_email = $2 AND dismissed = false`,
        [notificationId, email]
      );

      if (rowCount === 0) {
        return { success: false, message: 'Notification not found' };
      }
      return { success: true, message: `Snoozed for ${duration}` };
    } catch (err) {
      console.error('[snooze] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Dismiss a notification — soft-deletes it from all feeds. The row stays
   * in the table until the 30-day prune window cleans it up.
   */
  async dismiss(email, notificationId) {
    try {
      if (!pool) throw new Error('Database pool not initialized');
      if (!email || !notificationId) {
        return { success: false, message: 'email and notificationId are required' };
      }

      const { rowCount } = await pool.query(
        `UPDATE public.notifications
            SET dismissed = true, read = true
          WHERE id = $1 AND user_email = $2`,
        [notificationId, email]
      );

      if (rowCount === 0) {
        return { success: false, message: 'Notification not found' };
      }
      return { success: true, message: 'Notification dismissed' };
    } catch (err) {
      console.error('[dismiss] FAILED:', err.message);
      return { success: false, message: err.message };
    }
  }

  /**
   * Single transactional email via the Brevo HTTP API.
   * Rich HTML template with entry card, project badge, and deep-link button.
   * Returns true only when Brevo accepted the message.
   */
  async _sendBrevoEmail(apiKey, senderEmail, row) {
    const isOverdue = row.type === 'overdue';
    const title = row.entry_title || `${row.project_name || 'An'} entry`;
    const dueLabel = formatDueAt(row.due_at);
    const subject = isOverdue ? `Overdue: ${title}` : `Due soon: ${title}`;
    const accentColor = isOverdue ? '#dc2626' : '#d97706';
    const accentBg = isOverdue ? '#fef2f2' : '#fffbeb';
    const heading = isOverdue ? 'Deadline passed' : 'Deadline approaching';
    const statusLabel = isOverdue ? 'OVERDUE' : 'DUE SOON';
    const deepLink = row.project_name
      ? `${APP_URL}/project/${encodeURIComponent(row.project_name)}`
      : APP_URL;

    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 520px; margin: 0 auto; background: #f9fafb; padding: 32px 24px;">
        <div style="background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">
          <div style="background: ${accentColor}; padding: 16px 24px;">
            <span style="color: #ffffff; font-size: 11px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase;">${statusLabel}</span>
          </div>
          <div style="padding: 24px;">
            <h2 style="color: #111827; font-size: 18px; margin: 0 0 8px; font-weight: 600;">${escapeHtml(heading)}</h2>
            <div style="background: ${accentBg}; border-radius: 8px; padding: 16px; margin: 0 0 16px;">
              <p style="color: #111827; font-size: 15px; margin: 0 0 4px; font-weight: 500;">${escapeHtml(title)}</p>
              ${row.project_name ? `<p style="color: #6b7280; font-size: 13px; margin: 0 0 4px;">Project: ${escapeHtml(row.project_name)}</p>` : ''}
              ${dueLabel ? `<p style="color: ${accentColor}; font-size: 13px; font-weight: 500; margin: 0;">Due: ${escapeHtml(dueLabel)}</p>` : ''}
            </div>
            <a href="${escapeHtml(deepLink)}" style="display: inline-block; background: #111827; color: #ffffff; font-size: 14px; font-weight: 500; padding: 10px 20px; border-radius: 8px; text-decoration: none;">Open in Digital Logbook</a>
          </div>
          <div style="padding: 12px 24px; border-top: 1px solid #f3f4f6;">
            <p style="color: #9ca3af; font-size: 11px; margin: 0;">
              You're receiving this because email notifications are enabled in your Digital Logbook settings.
            </p>
          </div>
        </div>
      </div>`;

    try {
      const response = await fetch(BREVO_API_URL, {
        method: 'POST',
        headers: {
          'api-key': apiKey,
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify({
          sender: { email: senderEmail, name: 'Digital Logbook' },
          to: [{ email: row.user_email }],
          subject,
          htmlContent: html,
        }),
      });

      if (!response.ok) {
        const body = await response.text();
        console.error(`[sendPendingEmails] Brevo rejected ${row.id}: ${response.status} ${body}`);
        return false;
      }
      return true;
    } catch (err) {
      console.error(`[sendPendingEmails] Brevo call failed for ${row.id}:`, err.message);
      return false;
    }
  }
}

export default Notifications;
